version: "3.5"
services:
  beacon-chain:
    build:
      context: beacon-chain
      args:
        UPSTREAM_VERSION: v4.1.1
    volumes:
      - "beacon-chain-data:/data"
    ports:
      - "14503:14503/tcp"
      - "14503:14503/udp"
    restart: unless-stopped
    environment:
      CORSDOMAIN: "http://prysm-holesky.dappnode"
      CHECKPOINT_SYNC_URL: ""
      P2P_TCP_PORT: 14503
      P2P_UDP_PORT: 14503
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
  validator:
    build:
      context: validator
      dockerfile: Dockerfile
      args:
        UPSTREAM_VERSION: v4.1.1
    volumes:
      - "validator-data:/root/"
    restart: unless-stopped
    environment:
      LOG_TYPE: INFO
      BEACON_RPC_PROVIDER: "beacon-chain.prysm-holesky.dappnode:4000"
      BEACON_RPC_GATEWAY_PROVIDER: "beacon-chain.prysm-holesky.dappnode:3500"
      GRAFFITI: validating_from_DAppNode
      EXTRA_OPTS: ""
      FEE_RECIPIENT_ADDRESS: ""
volumes:
  beacon-chain-data: {}
  validator-data: {}
